- name: install docker
  hosts: host
  become: true
  tasks:
    - name: run docker
      docker_compose:
        project_src: ~/docker/docker
        files:
          - docker-compose.yaml
        build: true