- name: install docker
  hosts: host
  become: false
  tasks:
    - name: run docker
      docker_compose:
        project_src: ~/docker
        files:
          - docker-compose.yaml
        build: true