
---
- name: template
  import_playbook: commands/00-template.yaml
- name: install docker
  import_playbook: packages/01-docker.yaml
- name: install docker-compose
  import_playbook: packages/02-docker-compose.yaml
- name: copy folder
  import_playbook: commands/01-copy-folder.yaml
- name: run docker-compose
  import_playbook: commands/02-run-docker.yaml